export const Activator: string
export const activator: string
export const FadeActivator: string
export const fadeActivator: string
export const Hamburger: string
export const hamburger: string
export const MiddleLine: string
export const middleLine: string
export const hamburgerBeforeOut: string
export const hamburgerAfterOut: string
export const hamburgerMiddleOut: string
export const isExpanded: string
export const hamburgerBeforeIn: string
export const hamburgerAfterIn: string
export const hamburgerMiddleIn: string
export const skeletonShimmerAnimation: string
