export const TypeHeading: string
export const typeHeading: string
export const level1: string
export const level2: string
export const level3: string
export const level4: string
export const isInverse: string
export const PageNav: string
export const pageNav: string
export const Interior: string
export const interior: string
export const isOpened: string
export const List: string
export const list: string
export const Item: string
export const item: string
export const Link: string
export const link: string
export const SearchActivator: string
export const searchActivator: string
export const isCurrent: string
export const skeletonShimmerAnimation: string
